// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZ686lYWvDoDWpcKrecDd3A48_1o7RevU',
    appId: '1:537569368518:web:a3fcfef8050de777a6bac7',
    messagingSenderId: '537569368518',
    projectId: 'ensemble-dbb5d',
    authDomain: 'ensemble-dbb5d.firebaseapp.com',
    storageBucket: 'ensemble-dbb5d.appspot.com',
    measurementId: 'G-3NL8SF9W7V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwEjcSeASyF12MYGef3fg7QhtCgYBHSkA',
    appId: '1:537569368518:android:94977a6a448f0cb5a6bac7',
    messagingSenderId: '537569368518',
    projectId: 'ensemble-dbb5d',
    storageBucket: 'ensemble-dbb5d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPE1qWRq3FV3Ouds4sJs76bK-CZw2o1WQ',
    appId: '1:537569368518:ios:7aeff16f716bb280a6bac7',
    messagingSenderId: '537569368518',
    projectId: 'ensemble-dbb5d',
    storageBucket: 'ensemble-dbb5d.appspot.com',
    iosBundleId: 'com.ensemble.ensemble',
  );
}
